name: get-version

on:
  push:
    branches:
      - 'main'

jobs:
  build:
  
    name: get-version
    runs-on: ubuntu-latest
    
    permissions: 
      contents: read
      packages: read
      id-token: write
    
    steps:
    - name: Print env
      run: env | sort
    - name: Get version NPM
      id: get_version_npm
      uses: MintPlayer/github-actions/get-npmjs-version@main
      with:
        package_name: "@mintplayer/ng-bootstrap"
    - name: Log version
      run: echo ${{ steps.get_version_npm.outputs.packageInfo }}
    - name: Get version Github
      id: get_version_gpr
      uses: MintPlayer/github-actions/get-gpr-version@main
      with:
        package_name: "@mintplayer/ng-bootstrap"
        package_type: "npm"
        token: ${{ github.token }}
    - name: Log version
      run: echo ${{ steps.get_version_gpr.outputs.packageInfo }}
